### PR TITLE
Initial data class commit.

### LINKED ISSUE #27: Create basic data class structure that pulls from RSP
Groundwork of the basic class structure needs to be laid out. 

Currently the plan is to have an overarching AdlerPlanetoid class, which then instantiates and populates Observations (from DIASource and SSSource), MPCORB and SSObject objects with data from the RSP.  This allows all of the data from the RSP to be accessed in a manner that should be fairly intuitive to anyone familiar with the RSP schema.

Doing this for the full 10 years and a single filter will provide a baseline to work from.

### LINKED ISSUE #28: Add a main script that can be called on the command line
A script (e.g. adler.py) should be written which takes command line input and then runs whatever Adler business we want to run.

### PR DESCRIPTION
**Pull request by astronomerritt**
Fixes #27.
This PR begins the basic data class structure for Adler.

Fixes #28.
Adds a command line script so Adler can be called on the command line. Changed the file structure a bit.

I have tested that this all works on the RSP. Yay!

### CODE REVIEW

**Comment by astronomerritt** [comment]
Going to pull this branch down to the RSP and test it before I merge...

**Review by mschwamb — CHANGES_REQUESTED** [review]
Can you remove the .DS_Store files and add .DS_Store  to the .gitignore file - it's empty mac files and so we should not include them in the repository

**Review by jrob93 — APPROVED** [review]
Looks good to me, I think the data structure has everything I need for now. I agree with Meg on gitignoring local .DS_Store files

**Comment by astronomerritt** [comment]
Good catch. I'd assumed .DS_Store was in the .gitignore. That should be it now.

**Comment by mschwamb** [comment]
Still need to remove the .DS_store that already got pushed before this PR. Those still exist in the PR

**Comment by astronomerritt** [comment]
Argh. Sorry. That should be all of them now.

**Review by mschwamb — APPROVED** [review]

**Pull request merged**
