### PR TITLE
Initial commit of AdlerData class.

### LINKED ISSUE #53: Write the AdlerSchema class
The AdlerPlanetoid class needs an AdlerSchema class to store all the values calculated by the adler science modules. For example PhaseCurve will output H and G12 phase curve fits and these must be stored.

### LINKED ISSUE #63: Fix typo in SSObject class
The attribute `r_G12Err` is mistakenly called `r_G12_err` on initialisation.

### LINKED ISSUE #64: Remove the .to_table() call from DataSchema.get_RSP_table
So it turns out that simply running: 

```
service = get_tap_service("ssotap")
tab = service.search(<sql_query>)
```

results in a DALResultsTable object, from PyVO. If we then call, for example:

`tab['column_name']`

The result is a Numpy masked array, which is more or less what we're after (whether we remove the mask in favour of NaNs is another argument). 

So the to_table() call, which transforms the result into an AstroPy table, is completely unnecessary.

### LINKED ISSUE #67: Add num_obs to Observations object
See above.

### LINKED ISSUE #68: Change all instances of sys.exit to raise exceptions instead
We used `sys.exit("error message")` to end execution on errors with Sorcha, but this won't work in a Jupyter notebook.

Instead we should use:

`raise Exception("error message")`

You can also raise specific errors from the [concrete exception list](https://docs.python.org/3/library/exceptions.html#concrete-exceptions):

`raise ValueError("Incorrect value for parameter b")`

This works in a Jupyter notebook and also when running from the command line.

I should also add this to the dev guide.

### PR DESCRIPTION
**Pull request by astronomerritt**
Fixes #53.
- Created the AdlerData class, which will store all calculated AdlerData values.
- AdlerPlanetoid now creates an instance of the AdlerData class as a class attribute on initialisation
- Wrote a method, `AdlerData.populate_phase_parameters()`, which should allow for easy population.
- Wrote a unit test.

Fixes #68.
- Changed instances of `sys.exit()` to `raise Exception()` instead.

Fixes #67:
- num_obs has been added to the Observations object.

Fixes #63.
- Fixed a typo.

Fixes #64.
- Removed unnecessary `.to_table()` call.

## Review Checklist for Source Code Changes

- [x] Does pip install still work?
- [x] Have you written a unit test for any new functions?
- [x] Do all the units tests run successfully?
- [x] Does adler run successfully on a test set of input files/databases?
- [x] Have you used black on the files you have updated to confirm python programming style guide enforcement?

### CODE REVIEW

**Comment by astronomerritt** [comment]
Updated to make recommended changes.

**Comment by astronomerritt** [comment]
...and forgot to push. Done now.

**Comment by mschwamb** [comment]
instead of phase_parameter1 and phase_parameter2 what about

phase_parameters= [[parameter1,parameter2], [parameter1],] if we happen to be running multiple models.

**Comment by astronomerritt** [comment]
I was trying to avoid too many nested lists - this would mean that phase_parameter is nested three times, for filter, model and then parameter. I will still do this if you think it's best, but I worry about maintainability when someone who isn't me has to read the code.

**Comment by mschwamb** [comment]
phase_parameter_err  is a variable twice

**Comment by mschwamb** [comment]
Fair enough,but is nested better than having nulls or empty arrays when you don't have a parameter2 for 1 model

**Comment by astronomerritt** [comment]
Mistake in the docstring only, they're separate in the function. Correcting.

**Comment by astronomerritt** [comment]
> Fair enough,but is nested better than having nulls or empty arrays when you don't have a parameter2 for 1 model?

Point taken. I can make this change, one second.

**Comment by astronomerritt** [comment]
Done. In retrospect, now I've made the change I prefer it...

**Review by mschwamb — APPROVED** [review]
Looks good to me

**Pull request merged**
